baseURL = 'https://jimojiedeng.github.io/xg-blog/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = '小哥博客'

theme = 'hugo-zen'

paginate = 10

[languages]
  [languages.zh-cn]
    languageName = '中文'
    weight = 1

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 2

[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3
