baseURL = 'https://jimojiedeng.github.io/' 
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = '小哥博客'
theme = 'hugo-zen' 

[params]
  author = "你的名字"
  description = "记录生活与思考"

[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 20
